=begin pod

=head1 NAME

B<PS::Prepress> - Utilities for manipulating PostScript documents to prepare for printing (prepress)

=head1 SYNOPSIS

=begin code :lang<raku>

use PS::Prepress;

=end code

=head1 DESCRIPTION

PS::Prepress consists of several utilities converted to Raku from the Perl collection 'psutils' and C
program 'libpaper', both currently maintained by Reuben Thomas. Both are available on GitHub
at L<https://github.com/rrthomas/psutils> and L<https://github.com/rrthomas/libpaper>.

=head1 AUTHOR

Tom Browder <tbrowder@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2021 Tom Browder

This library is free software; you may redistribute it or modify it under the Artistic License 2.0.

=end pod
